### ISSUE TITLE
Dependecy issue

### ISSUE THREAD

**Issue by PiotrBerebecki** [wesbos/Learn-Redux#5]
Hi Wes,

I'm getting the following warning when doing the npm install from the package.json file.

`babel-eslint@5.0.4 requires a peer of eslint@<2.3.0 but none was installed.`

Have you got a suggested fix?

**Comment by IrineBrank** [comment]
I'm getting the following error when doing the npm install 

The package eslint does not satisfy its siblings' peerDependencies requirements!

**Comment by ultrox** [comment]
I had problems with css/stylus loader running it with:
`node v6.8.0 (npm v3.10.8)
`
_Error I was getting was:_
`Path must be a string. Received undefined
`
I fixed the problem with downgrading to node 5.0 via nvm.

**Comment by blakeperdue** [comment]
I got the same error as @ultrox. I'd rather not downgrade node in order to make this demo work. I wonder what dependency is failing.

This issue pretty much sums up my experience learning react. Everyone does things slightly different using different dependencies. Even one of the best "how to" guides on the web no longer works 11 months after release because some of these dependencies now have issues.

@wesbos maybe it's worth updating this repo to work with the latest node so that new learners will still be able to use this repo? Thanks!

**Comment by ultrox** [comment]
@blakeperdue, thanks for commenting. I was just trying to see something from this code base and needed fast solution to the problem, and figure out some other person would benefit from it, as stuff like this happened to me on daily basis and random people leaving their solution helped me tremendously.

What I don't understand is, if I install all dependencies in the right versions why app is broken, isn't that the point of installing  correct dependencies?

**Comment by blakeperdue** [comment]
@ultrox that's a great point. I tried installing the exact version of the dependencies but am still not able to get it work. I must be missing something.

**Comment by wesbos** [comment]
fixed

**Comment by blakeperdue** [comment]
Thank you @wesbos ! Appreciate the help.
